application/models/AdminModel.php
<?php

/**
 * 
 */
class AdminModel extends CI_Model
{
	
	function __construct()
	{
		parent::__construct();
	}

	function proses_login($where){
		return $this->db->get_where('tb_akses', $where);
	}

	function getAkses(){
		return $this->db->get('tb_akses');
	}

	function simpan_akses($where){
		return $this->db->insert('tb_akses', $where);
	}

	function getbyakses($id){
		$this->db->where('id_akses', $id);
		return $this->db->get('tb_akses');
	}
	function edit_akses($id, $where){
		$this->db->where('id_akses', $id);
		return $this->db->update('tb_akses', $where);
	}

	function delete_akses($id_akses){
		$this->db->where('id_akses', $id_akses);
		return $this->db->delete('tb_akses');
	}

	function getAgen(){
		return $this->db->get('tb_agen');
	}

	function getbyAgen($id){
		$this->db->where('id_agen', $id);
		return $this->db->get('tb_agen');
	}

	function simpan_agen($where){
		return $this->db->insert('tb_agen', $where);
	}

	function edit_agen($id, $where){
		$this->db->where('id_agen', $id);
		return $this->db->update('tb_agen', $where);
	}

	function delete_agen($id){
		$this->db->where('id_agen', $id);
		return $this->db->delete('tb_agen');
	}

	function getCustomer(){
		return $this->db->get('tb_customer');
	}

	function getbyCustomer($id){
		$this->db->where('id_customer', $id);
		return $this->db->get('tb_customer');
	}

	function simpan_customer($where){
		return $this->db->insert('tb_customer', $where);
	}

	function edit_customer($id, $where){
		$this->db->where('id_customer', $id);
		return $this->db->update('tb_customer', $where);
	}

	function delete_customer($id){
		$this->db->where('id_customer', $id);
		return $this->db->delete('tb_customer');
	}

	function getShipment(){
		return $this->db->get('tb_shipment');
	}

	function getbyShipment($id){
		$this->db->where('id_shipment', $id);
		return $this->db->get('tb_shipment');
	}

	function simpan_shipment($where){
		return $this->db->insert('tb_shipment', $where);
	}

	function edit_shipment($id, $where){
		$this->db->where('id_shipment', $id);
		return $this->db->update('tb_shipment', $where);
	}

	function delete_shipment($id){
		$this->db->where('id_shipment', $id);
		return $this->db->delete('tb_shipment');
	}

	function getJobs(){
		return $this->db->get("tb_jobs");
	}

	function simpan_jobs($where){
		return $this->db->insert('tb_jobs', $where);
	}

	function getbyJobs($id){
		return $this->db->query("SELECT * FROM tb_jobs INNER JOIN tb_customer ON tb_jobs.id_customer = tb_customer.id_customer WHERE tb_jobs.id_jobs = '$id'");
	}

	function getDataCustomer($id){
		return $this->db->query("SELECT * FROM tb_jobs INNER JOIN tb_customer ON tb_jobs.id_customer = tb_customer.id_customer WHERE tb_jobs.id_jobs = '$id'");
	}

	function edit_jobs($id, $where){
		$this->db->where('id_jobs', $id);
		return $this->db->update('tb_jobs', $where);
	}

	function getdatadesjob($id){
		$this->db->where('no_job', $id);
		return $this->db->get('tb_des_job');
	}
	
	function getdatadesjobinv($id){
		$this->db->where('no_job', $id);
		return $this->db->get('tb_des_inv');
	}

	function simpan_des_jobs($where){
		return $this->db->insert('tb_des_job', $where);
	}

	function edit_des_inv($id, $where)
	{
		$this->db->where('id_des_inv', $id);
		return $this->db->update('tb_des_inv', $where);
	}

	function hapus_des_jobs($id){
		$this->db->where('id_des_job', $id);
		return $this->db->delete('tb_des_job');
	}

	function delete_des_jobs($id){
		$this->db->where('no_job', $id);
		return $this->db->delete('tb_des_job');
	}

	function delete_jobs($id){
		$this->db->where('id_jobs', $id);
		return $this->db->delete('tb_jobs');
	}

	function getInvoice(){
		return $this->db->query("SELECT * FROM tb_invoice INNER JOIN tb_jobs ON tb_invoice.no_jobs = tb_jobs.no_job");
	}

	function getbyInvoice($id){
		$this->db->where('id_invoice', $id);
		return $this->db->get('tb_invoice');
	}

	function getDataInvoice($id){
		return $this->db->query("SELECT * FROM tb_invoice 
			INNER JOIN tb_jobs ON tb_invoice.no_jobs = tb_jobs.no_job 
			LEFT JOIN tb_customer ON tb_customer.id_customer = tb_jobs.id_customer 
			WHERE tb_invoice.id_invoice = '$id'");
	}

	function search_jobs($job){
		
		return $this->db->query("SELECT * FROM tb_jobs INNER JOIN tb_customer ON tb_jobs.id_customer = tb_customer.id_customer WHERE tb_jobs.no_job = '$job'");
	}

	function simpan_invoice($where){
		return $this->db->insert('tb_invoice', $where);
	}

	function simpan_invoice_kredit($data){
		return $this->db->insert('tb_hutang', $data);
	}

	function edit_invoice($id, $where){
		$this->db->where('id_invoice', $id);
		return $this->db->update('tb_invoice', $where);
	}

	function insert_piutang($id, $data){
		$get = $this->db->get_where('tb_piutang', ['id_invoice' => $id]);
		if($get->num_rows() > 0){
			$this->db->where('id_invoice', $id);
			return $this->db->update('tb_piutang', $data);
		}
		else{
			return $this->db->insert('tb_piutang', $data);
		}
	}

	function delete_invoice($id){
		$this->db->where('id_invoice', $id);
		return $this->db->delete('tb_invoice');
	}

	function simpan_des_invoice($where){
		return $this->db->insert('tb_des_inv', $where);
	}

	function getdatadesinvoice($id){
		$this->db->where('no_invo', $id);
		return $this->db->get('tb_des_inv');
	}

	function hapus_des_inv($id){
		$this->db->where('id_des_inv', $id);
		return $this->db->delete('tb_des_inv');
	}

	function delete_des_inv($id){
		$this->db->where('no_invo', $id);
		return $this->db->delete('tb_des_inv');
	}

	function getHutang(){
		return $this->db->get('tb_hutang');
	}

	function getbyHutang($id){
		$this->db->where('id_hutang', $id);
		return $this->db->get('tb_hutang');
	}

	function simpan_hutang($where){
		return $this->db->insert('tb_hutang', $where);
	}

	function edit_hutang($id, $where){
		$this->db->where('id_hutang', $id);
		return $this->db->update('tb_hutang', $where);
	}

	function hapus_hutang($id){
		$this->db->where('id_hutang', $id);
		return $this->db->delete('tb_hutang');
	}

	function getPiutang(){
		return $this->db->get('tb_piutang');
	}

	function getbyPiutang($id){
		$this->db->where('id_piutang', $id);
		return $this->db->get('tb_piutang');
	}

	function simpan_piutang($where){
		return $this->db->insert('tb_piutang', $where);
	}

	function edit_piutang($id, $where){
		$this->db->where('id_piutang', $id);
		return $this->db->update('tb_piutang', $where);
	}

	function hapus_piutang($id){
		$this->db->where('id_piutang', $id);
		return $this->db->delete('tb_piutang');
	}

	function bayar_piutang($id){
		$piutang = ['status' => "Lunas"];
		$this->db->where('id_piutang', $id);
		return $this->db->update('tb_piutang', $piutang);
	}

	function getBank(){
		return $this->db->get('tb_bank');
	}

	function getbyBank($id){
		$this->db->where('id_bank', $id);
		return $this->db->get('tb_bank');
	}

	function simpan_bank($where){
		return $this->db->insert('tb_bank', $where);
	}

	function edit_bank($id, $where){
		$this->db->where('id_bank', $id);
		return $this->db->update('tb_bank', $where);
	}

	function hapus_bank($id){
		$this->db->where('id_bank', $id);
		return $this->db->delete('tb_bank');
	}

	function getKasMasuk(){
		return $this->db->query("SELECT * FROM tb_kas_masuk INNER JOIN tb_bank ON tb_kas_masuk.id_bank = tb_bank.id_bank");
	}

	function simpan_kasmasuk($where){
		return $this->db->insert('tb_kas_masuk', $where);
	}

	function getBykMasuk($id){
		$this->db->where('id_kas_masuk', $id);
		return $this->db->get('tb_kas_masuk');
	}

	function edit_kasmasuk($id, $where){
		$this->db->where('id_kas_masuk', $id);
		return $this->db->update('tb_kas_masuk', $where);
	}

	function hapus_kas_masuk($id){
		$this->db->where('id_kas_masuk', $id);
		return $this->db->delete('tb_kas_masuk');
	}

	function getKasKeluar(){
		return $this->db->query("SELECT * FROM tb_kas_keluar INNER JOIN tb_bank ON tb_kas_keluar.id_bank = tb_bank.id_bank");
	}

	function simpan_kaskeluar($where){
		return $this->db->insert('tb_kas_keluar', $where);
	}

	function getBykKeluar($id){
		$this->db->where('id_kas_keluar', $id);
		return $this->db->get('tb_kas_keluar');
	}

	function edit_kaskeluar($id, $where){
		$this->db->where('id_kas_keluar', $id);
		return $this->db->update('tb_kas_keluar', $where);
	}

	function hapus_kas_keluar($id){
		$this->db->where('id_kas_keluar', $id);
		return $this->db->delete('tb_kas_keluar');
	}

	function getKasDebet(){
		return $this->db->query("SELECT * FROM tb_kas_debet INNER JOIN tb_bank ON tb_kas_debet.id_bank = tb_bank.id_bank");
	}

	function simpan_kasdebet($where){
		return $this->db->insert('tb_kas_debet', $where);
	}

	function getBykDebet($id){
		$this->db->where('id_kas_debet', $id);
		return $this->db->get('tb_kas_debet');
	}

	function edit_kasdebet($id, $where){
		$this->db->where('id_kas_debet', $id);
		return $this->db->update('tb_kas_debet', $where);
	}

	function hapus_kas_debet($id){
		$this->db->where('id_kas_debet', $id);
		return $this->db->delete('tb_kas_debet');
	}

	function getInvoiceByKredit(){
		return $this->db->query("SELECT * FROM tb_invoice LEFT JOIN tb_jobs ON tb_invoice.no_jobs = tb_jobs.no_job WHERE tb_invoice.type_pembayaran = 'Kredit'");
	}

	function edit_des_job($id, $data){
		$this->db->where('id_des_job', $id);
		return $this->db->update('tb_des_job', $data);
	}

	function edit_des_op($id, $data){
		$this->db->where('id_job_operational', $id);
		return $this->db->update('tb_job_opertaional', $data);
	}
}

?>

application/views/content_file/data_invoice.php
<!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
            <h4 class="page-title">Invoice</h4>
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">Home</a></li>
            <li class="breadcrumb-item"><a href="javaScript:void();">Jobs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Invoice</li>
         </ol>
       </div>
     </div>
    <!-- End Breadcrumb-->
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> List Invoice</div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="default-datatable" class="table table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>No. Invoice</th>
                        <th>Tgl</th>
                        <th>Job Number</th>
                        <th>Customer</th>
                        <th>No. MBL</th>
                        <th>VESSEL & VOY</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $no = 0;
                        foreach ($invoice as $key) {
                            $no++;
                    ?>
                    <tr>
                        <td><?php echo $no;?>.</td>
                        <td><?php echo $key->no_invoice;?></td>
                        <td><?php echo $key->date;?></td>
                        <td><?php echo $key->no_job;?></td>
                        <td><?php echo $key->customer;?></td>
                        <td><?php echo $key->mbl_no;?></td>
                        <td><?php echo $key->vessel_voy;?></td>
                        <td>
                            <a href="<?php echo site_url('UserController/cetak_invoice/');?><?php echo $key->id_invoice;?>" class="btn btn-outline-success" title="Edit" target="_blank"><i class="fa fa-print"></i> Invoice 1</a>
                             <a href="<?php echo site_url('UserController/cetak_invoice_2/');?><?php echo $key->id_invoice;?>" class="btn btn-outline-success" title="Edit" target="_blank"><i class="fa fa-print"></i> Invoice 2</a>
                           <!-- <a href="<?php echo site_url('UserController/page_home/edit_invoice/');?><?php echo $key->id_invoice;?>" class="btn btn-outline-primary" title="Edit"><i class="fa fa-edit"></i> Edit</a> -->
                            <button type="button" onclick="hapus_akses(<?php echo $key->id_invoice;?>)" class="btn btn-outline-danger"  title="Hapus"><i class="fa fa-trash"></i> Hapus</button>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->

      <script type="text/javascript">
          function hapus_akses(id_invoice){
                Swal.fire({
                  title: 'Apakah anda yakin?',
                  text: "Kamu ingin menghapus data ini!",
                  type: 'warning',
                  showCancelButton: true,
                  confirmButtonColor: '#3085d6',
                  cancelButtonColor: '#d33',
                  confirmButtonText: 'yakin!'
                }).then((result) => {
                  if (result.value) {
                    $.ajax({
                        "url" : "<?php echo site_url('UserController/hapus_invoice');?>",
                        "type" : "POST",
                        "dataType" : "json",
                        "data" : {
                            "id_invoice" : id_invoice
                        },
                        success:function(data){
                            if (data.alert == "success") {
                                swal.fire({
                                    type: 'success',
                                    title: 'Success',
                                    text: 'Data berhasil di hapus.....!'
                                })
                                .then((value) => {
                                    document.location = "<?php echo site_url('UserController/page_home/data_invoice');?>";
                                });
                            }else{
                                 swal.fire({
                                      type: 'error',
                                      title: 'Failed',
                                      text: 'Data gagal dihapus.....!'
                                  });
                            }
                        }

                    });
                  }
                })
                
          }
      </script>

application/views/content_file/data_kaskeluar.php
<!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
            <h4 class="page-title">Kas Keluar</h4>
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Kas Keluar</li>
         </ol>
       </div>

       <div class="col-sm-3">
           <div class="btn-group float-sm-right">
                <a href="<?php echo site_url('UserController/page_home/form_kas_keluar');?>" class="btn btn-outline-primary waves-effect waves-light"><i class="fa fa-plus mr-1"></i> Tambah Data</a>
                <a href="<?php echo site_url('export/aruskaskeluar/');?>" class="btn btn-outline-primary"><i class="fa fa-table mr-1"></i>Export Excel</a>
          </div>
        </div>
     </div>
    <!-- End Breadcrumb-->
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> List Kas Keluar</div>
            <div></div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="default-datatable" class="table table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Tgl</th>
                        <th>Deskripsi</th>
                        <th>Nama Bank</th>
                        <th>No. Rekening</th>
                        <th>Nominal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $no = 0;
                        foreach ($kkeluar as $key) {
                            $no++;
                    ?>
                    <tr>
                        <td><?php echo $no;?>.</td>
                        <td><?php echo $key->tgl_transaksi;?></td>
                        <td><?php echo $key->deskripsi;?></td>
                        <td><?php echo $key->nama_bank;?></td>
                        <td><?php echo $key->no_rekening;?></td>
                        <td><?php echo $key->nominal;?></td>
                        <td>
                            <a href="<?php echo site_url('UserController/page_home/form_kas_keluar/');?><?php echo $key->id_kas_keluar;?>" class="btn btn-outline-primary" title="Edit"><i class="fa fa-edit"></i> Edit</a>
                            <button type="button" onclick="hapus_akses(<?php echo $key->id_kas_keluar;?>)" class="btn btn-outline-danger"  title="Hapus"><i class="fa fa-trash"></i> Hapus</button>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->

      <script type="text/javascript">
          function hapus_akses(id_kas){
                Swal.fire({
                  title: 'Apakah anda yakin?',
                  text: "Kamu ingin menghapus data ini!",
                  type: 'warning',
                  showCancelButton: true,
                  confirmButtonColor: '#3085d6',
                  cancelButtonColor: '#d33',
                  confirmButtonText: 'yakin!'
                }).then((result) => {
                  if (result.value) {
                    $.ajax({
                        "url" : "<?php echo site_url('UserController/hapus_kas_keluar');?>",
                        "type" : "POST",
                        "dataType" : "json",
                        "data" : {
                            "id_kas" : id_kas
                        },
                        success:function(data){
                            if (data.alert == "success") {
                                swal.fire({
                                    type: 'success',
                                    title: 'Success',
                                    text: 'Data berhasil di hapus.....!'
                                })
                                .then((value) => {
                                    document.location = "<?php echo site_url('UserController/page_home/data_kaskeluar');?>";
                                });
                            }else{
                                 swal.fire({
                                      type: 'error',
                                      title: 'Failed',
                                      text: 'Data gagal dihapus.....!'
                                  });
                            }
                        }

                    });
                  }
                })
                
          }
      </script>

application/views/content_file/form_bank.php
<div class="row pt-2 pb-2">
    <div class="col-sm-9">
		    <h4 class="page-title">Form Input Saldo Awal</h4>
		    <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">Home</a></li>
            <li class="breadcrumb-item"><a href="javaScript:void();">Saldo Awal</a></li>
            <li class="breadcrumb-item active" aria-current="page">Form Input</li>
         </ol>
	   </div>
</div>
 <div class="row">
        <div class="col-lg-12">
          <div class="card">
             <div class="card-header text-uppercase">Form Input</div>
                <div class="card-body">
                  <div class="form-group row">
                    <label for="basic-input" class="col-sm-3 col-form-label">Nama Bank</label>
                    <div class="col-sm-9">
                    <input type="text" id="nama" value="<?php echo $nama;?>" class="form-control">
                    <input type="hidden" id="id_bank" value="<?php echo $this->uri->segment(4);?>" class="form-control">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="basic-input" class="col-sm-3 col-form-label">No. Rekening</label>
                    <div class="col-sm-9">
                    <input type="text" id="no_rekening" value="<?php echo $no_rekening;?>" class="form-control">
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <label for="placeholder-input" class="col-sm-3 col-form-label">Periode Awal</label>
                    <div class="col-sm-9">
                    <input type="text" id="periode_awal" class="form-control" value="<?php echo $periode_awal;?>" placeholder="dd/mm/yyyy">
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <label for="disabled-input" class="col-sm-3 col-form-label">Periode Akhir</label>
                    <div class="col-sm-9">
                    <input type="text" id="periode_akhir" class="form-control" value="<?php echo $periode_akhir;?>" placeholder="dd/mm/yyyy">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="disabled-input" class="col-sm-3 col-form-label">Jumlah Saldo</label>
                    <div class="col-sm-9">
                    <input type="text" id="jumlah_saldo" class="form-control" value="<?php echo $jumlah_saldo;?>" placeholder="0">
                    </div>
                  </div>
                  
                  <div class="form-group row mt-4">
                    <label for="staticEmail" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <button type="button" onclick="simpan_akses()" class="btn btn-primary shadow-primary px-5"><i class="fa fa-save"></i> <?php echo $btn;?></button>
                        <a href="<?php echo site_url('UserController/page_home/data_bank');?>" class="btn btn-danger shadow-primary px-5"><i class="fa fa-reply"></i> Kembali</a>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div><!--End Row-->

      <script type="text/javascript">
          
          function simpan_akses(){
              var nama_bank = $("#nama").val();
              var no_rekening = $("#no_rekening").val();
              var periode_awal = $("#periode_awal").val();
              var periode_akhir = $("#periode_akhir").val();
              var jumlah_saldo = $("#jumlah_saldo").val();
              var id_bank = $("#id_bank").val();

              if (nama_bank == "" || no_rekening == "" ||periode_awal == "" || periode_akhir == "" || jumlah_saldo == "") {
                  swal.fire({
                            type: 'warning',
                            title: 'Failed',
                            text: 'Silahkan lengkapi data bank.....!'
                        });
              }else{

                if (id_bank == "") {
                  $.ajax({
                    "url" : "<?php echo site_url('UserController/simpan_bank');?>",
                    "type" : "POST",
                    "dataType" : "json",
                    "data" : {
                        "nama_bank" : nama_bank,
                        "no_rekening" : no_rekening,
                        "periode_awal" : periode_awal,
                        "periode_akhir" : periode_akhir,
                        "jumlah_saldo" : jumlah_saldo
                    },
                    success:function(data){
                        if (data.alert == "success") {
                            swal.fire({
                                type: 'success',
                                title: 'Success',
                                text: 'Data berhasil tersimpan.....!'
                            })
                            .then((value) => {
                                document.location = "<?php echo site_url('UserController/page_home/data_bank');?>";
                            });
                        }else{
                             swal.fire({
                                  type: 'error',
                                  title: 'Failed',
                                  text: 'Data yang anda masukkan salah, silahkan cek kembali.....!'
                              });
                        }
                    }

                  });
                }else{
                    $.ajax({
                    "url" : "<?php echo site_url('UserController/edit_bank');?>",
                    "type" : "POST",
                    "dataType" : "json",
                    "data" : {
                        "nama_bank" : nama_bank,
                        "no_rekening" : no_rekening,
                        "periode_awal" : periode_awal,
                        "periode_akhir" : periode_akhir,
                        "jumlah_saldo" : jumlah_saldo,
                        "id_bank" : id_bank
                    },
                    success:function(data){
                        if (data.alert == "success") {
                            swal.fire({
                                type: 'success',
                                title: 'Success',
                                text: 'Data berhasil diedit.....!'
                            })
                            .then((value) => {
                                document.location = "<?php echo site_url('UserController/page_home/data_bank');?>";
                            });
                        }else{
                             swal.fire({
                                  type: 'error',
                                  title: 'Failed',
                                  text: 'Data yang anda masukkan salah, silahkan cek kembali.....!'
                              });
                        }
                    }

                  });
                }
              }
          }

      </script>
      <script type="text/javascript">
    
        var rupiah2 = document.getElementById('jumlah_saldo');
        rupiah2.addEventListener('keyup', function(e){
          // tambahkan 'Rp.' pada saat form di ketik
          // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
          rupiah2.value = formatRupiah2(this.value, '');
        });
     
        /* Fungsi formatRupiah */
        function formatRupiah2(angka, prefix){
          var number_string = angka.replace(/[^,\d]/g, '').toString(),
          split       = number_string.split(','),
          sisa        = split[0].length % 3,
          rupiah        = split[0].substr(0, sisa),
          ribuan        = split[0].substr(sisa).match(/\d{3}/gi);
     
          // tambahkan titik jika yang di input sudah menjadi angka ribuan
          if(ribuan){
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
          }
     
          rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
          return prefix == undefined ? rupiah : (rupiah ? '' + rupiah : '');
        }
      </script>

application/views/content_file/laporan_hutang.php
<!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
            <h4 class="page-title">Laporan Hutang</h4>
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Laporan Hutang</li>
         </ol>
       </div>

       <div class="col-sm-3">
           <div class="btn-group float-sm-right">
                <a href="<?php echo site_url('export/laporanhutang/');?>" class="btn btn-outline-primary"><i class="fa fa-table mr-1"></i>Export Excel</a>
          </div>
        </div>

     </div>
    <!-- End Breadcrumb-->
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> List Hutang</div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="default-datatable" class="table table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Tanggal Awal</th>
                        <th>Tanggal Jatuh Tempo</th>
                        <th>Nominal</th>
                        <th>Klien</th>
                        <th>Deskripsi</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $no = 0;
                        foreach ($hutang as $key) {
                            $no++;
                    ?>
                    <tr>
                        <td><?php echo $no;?>.</td>
                        <td><?php echo $key->tanggal_awal;?></td>
                        <td><?php echo $key->tgl_jatuh_tempo;?></td>
                        <td><?php echo "Rp ".number_format($key->nominal,2,',','.');?></td>
                        <td><?php echo $key->klien;?></td>
                        <td><?php echo $key->deskripsi;?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div>

application/views/content_file/laporan_kas_keluar.php
<!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
            <h4 class="page-title">Laporan Kas Keluar</h4>
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Laporan Kas Keluar</li>
         </ol>
       </div>
     </div>
    <!-- End Breadcrumb-->
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> List Kas Keluar</div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="default-datatable" class="table table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Tgl</th>
                        <th>Deskripsi</th>
                        <th>Nama Bank</th>
                        <th>No. Rekening</th>
                        <th>Nominal</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $no = 0;
                        foreach ($kkeluar as $key) {
                            $no++;
                    ?>
                    <tr>
                        <td><?php echo $no;?>.</td>
                        <td><?php echo $key->tgl_transaksi;?></td>
                        <td><?php echo $key->deskripsi;?></td>
                        <td><?php echo $key->nama_bank;?></td>
                        <td><?php echo $key->no_rekening;?></td>
                        <td><?php echo $key->nominal;?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->